/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.ArrayList;
import javax.swing.JOptionPane;
import br.com.estudo.persistence.PerguntasDAO;
import java.awt.Color;
import java.util.Collection;
import java.util.Collections;

/**
 *
 * @author Rick-Note
 */
public class TelaPrograma extends javax.swing.JFrame {

    /**
     *
     * Creates new form TelaPrograma
     */
    int index = 0;
    ArrayList<Perguntas> lista = new ArrayList<>();
    ArrayList<Perguntas> listaErros = new ArrayList<>();
    boolean treinaErros = false;
    boolean confere = true;
    int erros = 0;
    int acertos = 0;

    public TelaPrograma() {
        initComponents();
        
//        TelaCadPanel tela = new TelaCadPanel();
//        this.pnPrincipal.add(tela);
        
        this.setExtendedState(MAXIMIZED_BOTH);
        lblPergunta.setVisible(false);
        lblResposta.setVisible(false);
        btnConfere.setVisible(false);
        txtPergunta.setVisible(false);
        txtResposta.setVisible(false);
        txtRespCorreta.setVisible(false);

        getRootPane().setDefaultButton(btnComeca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnComeca = new javax.swing.JButton();
        lblPergunta = new javax.swing.JLabel();
        lblResposta = new javax.swing.JLabel();
        btnConfere = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRespCorreta = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPergunta = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtResposta = new javax.swing.JTextPane();
        lblErros = new javax.swing.JLabel();
        lblMostrador = new javax.swing.JLabel();
        lblAcertos = new javax.swing.JLabel();
        pnPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnCad = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTUDO DE ENGENHARIA DE SOFTWARE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 20, 620, 57);

        btnComeca.setBackground(new java.awt.Color(51, 255, 51));
        btnComeca.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnComeca.setText("COMEÇAR");
        btnComeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComecaActionPerformed(evt);
            }
        });
        getContentPane().add(btnComeca);
        btnComeca.setBounds(510, 410, 149, 53);

        lblPergunta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPergunta.setText("PERGUNTA: ");
        getContentPane().add(lblPergunta);
        lblPergunta.setBounds(70, 90, 126, 34);

        lblResposta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblResposta.setText("RESPOSTA:");
        getContentPane().add(lblResposta);
        lblResposta.setBounds(80, 230, 126, 34);

        btnConfere.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnConfere.setText("Conferir Resposta");
        btnConfere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfereActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfere);
        btnConfere.setBounds(830, 420, 195, 44);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("RESPOSTA CORRETA:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 460, 200, 30);

        txtRespCorreta.setEditable(false);
        txtRespCorreta.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtRespCorreta.setForeground(new java.awt.Color(0, 102, 0));
        jScrollPane3.setViewportView(txtRespCorreta);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(220, 470, 810, 170);

        txtPergunta.setEditable(false);
        txtPergunta.setBorder(null);
        txtPergunta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jScrollPane4.setViewportView(txtPergunta);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(180, 100, 850, 110);

        txtResposta.setBorder(null);
        txtResposta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtResposta.setForeground(new java.awt.Color(0, 0, 204));
        jScrollPane5.setViewportView(txtResposta);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(180, 240, 850, 160);

        lblErros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblErros.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lblErros);
        lblErros.setBounds(1040, 180, 260, 30);

        lblMostrador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(lblMostrador);
        lblMostrador.setBounds(1040, 100, 260, 30);

        lblAcertos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAcertos.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(lblAcertos);
        lblAcertos.setBounds(1040, 140, 260, 30);
        getContentPane().add(pnPrincipal);
        pnPrincipal.setBounds(0, 0, 1320, 760);

        jMenu1.setText("Menu");

        mnCad.setText("Cadastro de Pergunta");
        mnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadActionPerformed(evt);
            }
        });
        jMenu1.add(mnCad);

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadActionPerformed

        TelaCad cad = new TelaCad();
        cad.setVisible(true);

    }//GEN-LAST:event_mnCadActionPerformed

    private void btnComecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComecaActionPerformed
        if (!treinaErros) {
            btnComeca.setVisible(false);
            lblPergunta.setVisible(true);
            lblResposta.setVisible(true);
            btnConfere.setVisible(true);
            txtPergunta.setVisible(true);
            txtResposta.setVisible(true);
            index = 0;
            erros = 0;
            acertos = 0;

            PerguntasDAO objPerg = new PerguntasDAO();
            lista = objPerg.carregaLista();

            txtPergunta.setText(lista.get(index).getPergunta());

            lblMostrador.setText("QUESTÃO  " + (index + 1) + "  de  " + lista.size());

            getRootPane().setDefaultButton(btnConfere);
        } else {
            btnComeca.setVisible(false);
            lblPergunta.setVisible(true);
            lblResposta.setVisible(true);
            btnConfere.setVisible(true);
            txtPergunta.setVisible(true);
            txtResposta.setVisible(true);
            index = 0;
            erros = 0;
            acertos = 0;

            txtPergunta.setText(lista.get(index).getPergunta());

            lblMostrador.setText("QUESTÃO  " + (index + 1) + "  de  " + lista.size());

            getRootPane().setDefaultButton(btnConfere);
        }
        lblMostrador.setText("QUESTÃO  " + (index + 1) + "  de  " + lista.size());
        lblErros.setText("Resp. Erradas:  " + (erros));
        lblAcertos.setText("Resp. Certas:  " + (acertos));
        txtResposta.requestFocus();

    }//GEN-LAST:event_btnComecaActionPerformed

    private void btnConfereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfereActionPerformed

        if (!confere) {
            txtResposta.setText("");
            txtRespCorreta.setText("");
            btnConfere.setText("Conferir Resposta");
            txtRespCorreta.setVisible(false);
            txtResposta.requestFocus();
            if (index < lista.size()) {
                if (index == (lista.size() - 1)) {
                    btnConfere.setForeground(Color.red);
                    btnConfere.setText("Confere e Encerra.");
                }
                txtPergunta.setText(lista.get(index).getPergunta());
            } else {
                txtPergunta.setText("");
                btnComeca.setVisible(true);
                btnConfere.setVisible(false);

                int resposta = JOptionPane.showConfirmDialog(null, "Deseja Treinar as respostas erradas?", "Janela de Confirmação", JOptionPane.YES_NO_OPTION);

                if (resposta == JOptionPane.YES_OPTION) {
                    treinaErros = true;
                    lista.clear();
                    for (Perguntas x : listaErros) {
                        lista.add(x);
                    }
                    listaErros.clear();
                    Collections.shuffle(lista);
                    erros = 0;
                    acertos = 0;
                    index = 0;

                } else {
                    treinaErros = false;
                    erros = 0;
                    acertos = 0;
                    index = 0;
                }
                btnConfere.setText("Conferir Resposta");
                btnConfere.setForeground(Color.BLACK);
                getRootPane().setDefaultButton(btnComeca);
            }
            lblMostrador.setText("QUESTÃO  " + (index + 1) + "  de  " + lista.size());
            confere = true;
        } else {
            btnConfere.setText("Próxima Pergunta");
            txtRespCorreta.setVisible(true);
            txtRespCorreta.setText(lista.get(index).getResposta());
            int resposta = JOptionPane.showConfirmDialog(null, "Você acertou a resposta?", "Janela de Confirmação", JOptionPane.YES_NO_OPTION);

            if (resposta == JOptionPane.YES_OPTION) {
                acertos++;
                lblAcertos.setText("Resp. Certas:  " + (acertos));
                if (index != lista.size()) {
                    index++;
                }
            } else {
                erros++;
                lblErros.setText("Resp. Erradas:  " + (erros));
                listaErros.add(lista.get(index));
                index++;
            }
            confere = false;
        }
    }//GEN-LAST:event_btnConfereActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrograma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComeca;
    private javax.swing.JButton btnConfere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAcertos;
    private javax.swing.JLabel lblErros;
    private javax.swing.JLabel lblMostrador;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JMenuItem mnCad;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JTextPane txtPergunta;
    private javax.swing.JTextPane txtRespCorreta;
    private javax.swing.JTextPane txtResposta;
    // End of variables declaration//GEN-END:variables
}
