/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estudafacil.view;

import br.com.estudafacil.controller.MateriasDAO;
import br.com.estudafacil.model.Materias;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.Collator;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Rick-Note
 */
public class PanelCadMateriaDeleta extends javax.swing.JPanel {

    BufferedImage imagem;
    ArrayList<Materias> lista = new ArrayList<>();

    /**
     * Creates new form PanelCadMateriaSalva
     */
    public PanelCadMateriaDeleta() {
        initComponents();

        try {
            this.imagem = ImageIO.read(new File("src/botoes/boneco_apagando.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(PanelCadMateriaDeleta.class.getName()).log(Level.SEVERE, null, ex);
        }

        /**
         * CARREGA LISTA DE MATÉRIAS CADASTRADAS
         */
        MateriasDAO dao = new MateriasDAO();

        lista.clear();
        jcbMaterias.removeAllItems();
        lista = dao.carregaMaterias();
        jcbMaterias.addItem("Selecione...");

        for (Materias x : lista) {
            jcbMaterias.addItem(x.getMateria());
        }

    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(imagem, 0, 0, this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMateria = new javax.swing.JLabel();
        btnDeletar = new javax.swing.JButton();
        jcbMaterias = new javax.swing.JComboBox<>();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(456, 185));
        setMinimumSize(new java.awt.Dimension(456, 185));
        setPreferredSize(new java.awt.Dimension(456, 185));

        lblMateria.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblMateria.setText("Matéria:");

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes/lixo.png"))); // NOI18N
        btnDeletar.setText("EXCLUIR");
        btnDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

        if (jcbMaterias.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma Matéria antes de clicar em 'Deletar'.");
        } else {
            MateriasDAO dao = new MateriasDAO();
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja Excluir a Matéria: '" + jcbMaterias.getSelectedItem() + "'?", "Janela de Confirmação", JOptionPane.YES_NO_OPTION);

            if (resposta == JOptionPane.YES_OPTION) {
                dao.deletaMateria((String) jcbMaterias.getSelectedItem());
                lista.clear();
                jcbMaterias.removeAllItems();

                jcbMaterias.addItem("Selecione...");
                lista = dao.carregaMaterias();

                for (Materias x : lista) {
                    jcbMaterias.addItem(x.getMateria());
                }
            }

        }


    }//GEN-LAST:event_btnDeletarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    public javax.swing.JComboBox<String> jcbMaterias;
    private javax.swing.JLabel lblMateria;
    // End of variables declaration//GEN-END:variables
}
